version: "3.7"

services:
  app:
    build:
      context: .docker/app
      args:
        version_php: ${VERSION_PHP}
        version_xdebug: ${VERSION_XDEBUG}
        version_node: ${VERSION_NODE}
        version_glpi: ${VERSION_GLPI}
    volumes:
      - ./volumes/glpi:/var/www/html
      - ~/.composer:/root/.composer/
      - ~/.npm:/root/.npm/
      - ./.docker/app/xdebug.ini:/usr/local/etc/php/conf.d/xdebug.ini
    env_file:
      - .env
    environment:
      - TZ
      - GLPI_VERSION
      - XDEBUG_CONFIG
  web:
    build: .docker/web
    volumes:
      - ./volumes/glpi:/var/www/html
    ports:
      - ${PORT_WEB}:80
  mysql:
    image: mariadb
    volumes:
      - ./.docker/mysql/conf:/etc/mysql/conf.d
      - ./volumes/mysql/dump:/docker-entrypoint-initdb.d
      - ./volumes/mysql/data:/var/lib/mysql
    ports:
      - ${PORT_MYSQL}:3306
    environment:
      - TZ
      - MYSQL_HOST
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD