services:
  app:
    image: lyseontech/glpi:app-${VERSION_GLPI}
    # build:
    #   context: .docker/app
    #   args:
    #     version_php: ${VERSION_PHP}
    #     version_glpi: ${VERSION_GLPI}
    volumes:
      - ./volumes/glpi:/var/www/glpi
      - ./volumes/var:${GLPI_VAR_DIR}
      - ./volumes/config:${GLPI_CONFIG_DIR}
      - ~/.composer:/root/.composer/
      - ~/.npm:/root/.npm/
    env_file:
      - .env
    restart: unless-stopped
    environment:
      - TZ
      - HOST_UID=${HOST_UID:-1000}
      - HOST_GID=${HOST_GID:-1000}
      - GLPI_VERSION
      - GLPI_VAR_DIR
      - GLPI_CONFIG_DIR
      - EXTRA_COMMANDS
      - MYSQL_HOST
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
      - XDEBUG_CONFIG
    extra_hosts:
      - host.docker.internal:host-gateway
  web:
    image: lyseontech/glpi:nginx-${VERSION_GLPI}
    # build: .docker/web
    volumes:
      - ./volumes/glpi:/var/www/glpi
    ports:
      - ${PORT_WEB}:80
    restart: unless-stopped
  mysql:
    image: mariadb:11.0.2
    volumes:
      - ./.docker/mysql/conf:/etc/mysql/conf.d
      - ./volumes/mysql/dump:/docker-entrypoint-initdb.d
      - ./volumes/mysql/data:/var/lib/mysql
    ports:
      - ${PORT_MYSQL}:3306
    restart: unless-stopped
    environment:
      - TZ
      - MYSQL_HOST
      - MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
  cron:
    # image: lyseontech/glpi:app-${VERSION_GLPI}
    build:
      context: .docker/app
      args:
        version_php: ${VERSION_PHP}
        version_xdebug: ${VERSION_XDEBUG}
        version_node: ${VERSION_NODE}
        version_glpi: ${VERSION_GLPI}
    restart: unless-stopped
    environment:
      - TZ
      - HOST_UID=${HOST_UID:-1000}
      - HOST_GID=${HOST_GID:-1000}
      - GLPI_VERSION
      - EXTRA_COMMANDS
      - MYSQL_HOST
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_PASSWORD
    volumes:
      - ./volumes/glpi:/var/www/glpi
    entrypoint: /usr/src/glpi-scripts/cron.sh
